ethanmoffat/etheos

CMakeLists.txt
build-linux.sh
cmake/SourceFileList.cmake

- google test failed to compile since the CXX standard was set after the google test project was included
- test flag on linux was only printing the name of the test exe instead of running tests
- added copy for local configs (config_local directory) on install target

Fix Linux build issues. gtest compilation failure, test flag, and copying local configs to install directory

---

src/sln.cpp

SLN is designed to repeatedly kick off request threads on a timer. Only the first request is created when it is declared static. Removing static keyword so subsequent requests get created properly and SLN works as expected.

Remove static keyword from SLN request thread to prevent errors when re-queueing SLN requests

---

.vscode/c_cpp_properties.json
CMakeLists.txt
cmake/DownloadBcrypt.cmake
cmake/SourceFileList.cmake
cmake/bcryptproj.cmake
config/server.ini
install.sql
install_sqlserver.sql
src/database.cpp
src/eoserv_config.cpp
src/hash.cpp
src/hash.hpp
src/hashupdater.cpp
src/hashupdater.hpp
src/player.cpp
src/util/semaphore.cpp
src/util/semaphore.hpp
src/world.cpp
src/world.hpp
tu/system.cpp
upgrade/0.7.0_to_0.7.1.sql
upgrade/0.7.0_to_0.7.1_sqlserver.sql

Add support for versioned passwords. This allows implementing different password hashes with ease and versioning them in the database. The latest password version is stored (right now 1 == sha256, 2 == bcrypt) along with the hashed password.
As this requires a schema update to the database, I'm unofficially calling this v0.7.1.
Bcrypt implementation is https://github.com/trusch/libbcrypt, downloaded via CMake.
Password versions are updated on login in a background thread. A separate database connection is used for background thread updates.
This addresses [issue 431](https://eoserv.net/bugs/view_bug/431) on the eoserv bug tracker.

Support versioned passwords

---

.editorconfig

This patch adds a simple `.editorconfig` file to state expected file formatting parameters and improve the rendering of files when viewed on GitHub.
(Resolves #11)

Added EditorConfig file.

---

.vscode/c_cpp_properties.json
.vscode/launch.json
CMakeLists.txt
build-linux.sh
build-windows.ps1
cmake/SourceFileList.cmake
config/server.ini
scripts/install-deps.sh
src/character.cpp
src/character.hpp
src/commands/server.cpp
src/database.cpp
src/eoclient.cpp
src/eoserv_config.cpp
src/handlers/Account.cpp
src/handlers/Init.cpp
src/handlers/Talk.cpp
src/hashupdater.cpp
src/hashupdater.hpp
src/main.cpp
src/map.cpp
src/quest.cpp
src/test/util/semaphore_test.cpp
src/test/util/threadpool_test.cpp
src/util/semaphore.cpp
src/util/semaphore.hpp
src/util/threadpool.cpp
src/util/threadpool.hpp
tu/system.cpp

Threadpool replaces the previous implementation of PaswordHashUpdater and encapsulates the background thread/signaling functionality that queued incoming password version updates. Now, the work is queued on the Threadpool and most of the logic from PasswordHashUpdater is handled by the Threadpool.
Number of threads in the pool defaults to number of CPUs on the system. This can be overridden by a config value but shall not exceed 32 (arbitrarily chosen).
Additionally a bug in semaphore was fixed that did not release the proper number of claims. Semaphore also now has a maximum count that is honored when releasing.

Add threadpool for queueing of background operations asynchronously

---

src/map.cpp
src/quest.cpp
src/test/util/threadpool_test.cpp
src/util/threadpool.cpp
src/util/threadpool.hpp

Tests in threadpool failed to link due to static constexpr definitions in the header file. Not sure why this worked in msbuild but not gcc.
Also fixed a couple warnings using sprintf when building on Linux.

Fix linker error when building threadpool_test on Linux

---

CMakeLists.txt

Building on windows fails on my machine when linking against MariaDB unless `crypt32` and `secur32` are included.
This PR adds `crypt32` and `secur32` to `eoserv_LIBRARIES` when linking against MariaDB on windows.

Fix linking mariadb on windows

---

.editorconfig

EOSERV uses tabs rather than spaces in C++ source code.
The `.editorconfig` file specifies `indent_style = space`. This gets picked up by Visual Studio and leads to mixed spaces and tabs.
This PR overrides the `indent_style` for C++ source code files.

Use tabs for indentation in C++ source code

---

.gitattributes
README.md
azure-pipelines.yml
build-windows.ps1
cmake/FindMariaDB.cmake
cmake/SourceFileList.cmake
data/pub/empty.ecf
data/pub/empty.eif
data/pub/empty.enf
data/pub/empty.esf
scripts/install-deps.ps1
src/database.hpp
src/test/testhelper/mocks.hpp
src/test/testhelper/setup.hpp

- Support for multiple versions of Visual Studio and detection via vswhere (added to install-deps script)
- Build pipeline that builds release mode for Windows and Linux
- Forced support for all database engines in build pipeline
- Empty pub files copied by default to ensure tests pass on a clean system with no pub files installed

Add CI build support

---

CMakeLists.txt
azure-pipelines.yml
build-windows.ps1
cmake/DownloadBcrypt.cmake
cmake/DownloadGoogleTest.cmake
src/test/handlers/Login_test.cpp
src/test/util/threadpool_test.cpp

- Add offline build option for building with no internet connection (requires dependencies to be downloaded, including gtest and bcrypt)
- Add weekly scheduled build
- Increase timeout for a Login test so fast PCs don't clean up test before it finishes running
- Add counting semaphore for a ThreadPool test to ensure test only terminates when it is actually done

Fix unit tests on fast pcs

---

.gitignore
.vscode/c_cpp_properties.json
.vscode/tasks.json
CMakeLists.txt
cmake/SourceFileList.cmake
config/server.ini
scripts/install-deps.ps1
scripts/install-deps.sh
src/character.cpp
src/character.hpp
src/database.hpp
src/eoserv_config.cpp
src/fwd/character.hpp
src/main.cpp
src/player.cpp
src/player.hpp
src/test/handlers/Login_test.cpp
src/test/testhelper/mocks.hpp
src/test/testhelper/setup.hpp
src/test/worlddump_test.cpp
src/world.cpp
src/world.hpp

Add support for dumping and restoring the world object when server shuts down and starts. Both graceful and ungraceful shutdown cases will capture a crash dump in the configured file location. This file is formatted as json. A new dependency is added to `nlohmann::json` (installed via the `install-dependencies` script for a given platform).
Crash dump occurs when server throws an exception or traps a fatal signal. It also happens unconditionally on graceful shutdown of the server. When launching, the dump file is examined if it exists and state is restored. Characters, guilds, map items, and chest items are captured for restoration. NPC state is not captured since this is much more dynamic.
Characters will not be restored if an existing character in the database has a higher `usage` …

Add support for automatic dump/restore of world. Remove long-running open database transaction.

---

CMakeLists.txt
Dockerfile
azure-pipelines.yml
scripts/install-deps.sh
src/eoserv_config.cpp
src/eoserv_windows.h
src/test/config_test.cpp
src/test/testhelper/setup.hpp
src/version.h

Build pipeline will automatically push and tag a docker image with the build version number. Non-CI builds will tag dev/branchname, CI builds will tag test/branchname (for eventual deployment to kubernetes)
Includes these additional changes:
- Update version to 0.7.1 everywhere
- Use 'etheos' instead of 'eoserv'
- Allow for overriding config values from environment variables, in format of ETHEOS_{configkey} (uppercase)

Add dockerfile and docker build/push to azure pipelines

---

cmake/gtestproj.cmake

The GoogleTest repo has changed its default branch from master to main.

Change gtest branch from master to main

---

src/config.cpp
src/config.hpp
src/eoserv_config.cpp
src/test/config_test.cpp

Allows for any key to be loaded from environment, not just keys that have a default in eoserv_config.cpp

Load config values from environment on config read instead of on setting default config

---

src/database.cpp
src/database.hpp

Option wasn't working if there was more than one SQL error and the last error wasn't the "missing database" code, since only the last error code was being captured.

Fix AutoCreateDatabase functionality for SQL Server

---

azure-pipelines.yml
deploy/deploy.sh
deploy/etheos-ci-test.json
deploy/etheos-container.json
deploy/params-ci-test.json

Deploys to separate environment in azure. Relies on databases that are also deployed (as containers) via the ARM template. ARM template for dev/test/prod no longer supports deploying to ci-test since the ci-test files are now separate.

Add deployment to CI test environment

---

azure-pipelines.yml
deploy/deploy.sh
deploy/test-connection.py

Got hit with a rather large Azure spend bill due to the CI test environment always being up. Since it isn't really necessary to have up all the time I think it's safe to tear it down when it isn't actively being used. This adds a step to the build to tear down the CI test environment after CI tests run.

Tear down CI environment when not in use. Reduces Azure spend.

---

src/quest.cpp
src/quest.hpp

Trivial fix for an oversight in the data type used for `Quest_Context::TalkedNPC`.
See: https://eoserv.net/bugs/view_bug/444

Fix bug where `TalkedToNpc` breaks for NPC vendor IDs above 127

---

.vscode/launch.json
src/packet.cpp
src/socket.cpp

Addresses two asserts that show up when debugging on windows
1. `setsockopt` was incorrectly casting the value of `1` to `char *` and passing this as the `optval` parameter. Instead, the address of the `1` value is passed
2. `GetNumber` during packet reading was incorrectly incrementing beyond the length of the packet, which would cause subsequent calls to `copy_n` in `GetNumber` to fail because data was out of bounds.

Fix MSVC debug asserts

---

src/commands/server.cpp

Fixes crash bug when character that initiated the reload/shutdown disconnects before the reload/shutdown executes.
Will need to rely on admin command audit log to determine who is causing shutdowns/reloads

Avoid command source pointer dereference during reload/shutdown

---

src/handlers/Marriage.cpp

If an invalid fiance name with length >16 is sent with the `MARRIAGE_OPEN` packet, it causes `Character::Save` to fail.

Validate fiance names when buying marriage approval

---

config/server.ini
src/eoclient.cpp
src/eoclient.hpp
src/eoserv_config.cpp
src/eoserver.cpp
src/eoserver.hpp
src/handlers/Connection.cpp
src/handlers/Init.cpp
src/socket.cpp
src/socket.hpp
src/world.cpp

- Adds HangupDelay config option (default 10 seconds) to automatically close uninitialized connections
- Adds QuietConnectionErrors config option (default off) to group together repeated connection failure log lines from the same IP
- Allows adjusting MaxConnections and PingRate via $rehash
- Fixes the MaxConnections check on client accept
- Removes the "too many connections to server" connection failure on init
- Closes uninitialized clients, starting from the oldest, to make room for new clients if possible

Add mitigations for connection spam

---

Dockerfile
scripts/install-deps.sh
src/database.cpp

Adds Alpine 3.17.2 support to dependency install script, with the exception of CMake installation

Change Docker image to use Alpine base image and nonroot user

---

src/wedding.cpp

Deleting a timer event in the middle of `Timer::Tick` is probably a bad idea.
I have not tested this change.

Fix double-free bug in weddings
